"""Trim the generator output to what the site ships (provenance script; paths are absolute on the author's machine).
Drops look-dev helpers + example imports, and the per-node sculptComponent / lookDevTargets metadata blobs."""
import re, sys
p = sys.argv[1]
s = open(p).read()
s = re.sub(r"^import \{ (RoomEnvironment|EffectComposer|RenderPass|BokehPass|UnrealBloomPass|OrbitControls) \} from .*\n", "", s, flags=re.M)
cut = s.index("export function createTriviqTCoreLookDevLights(")
s = s[:cut].rstrip() + "\n"
s = re.sub(r"^\s*\w+\.userData\.(sculptComponent|lookDevTargets) = .*\n", "", s, flags=re.M)
s = re.sub(r"  root\.userData\.actionReadiness = \{\n.*?\n  \};\n", "", s, flags=re.S)
s = "/* eslint-disable @typescript-eslint/no-explicit-any -- generated by img2threejs (design/triviq-core) */\n" + s
open(p, "w").write(s)
